# Generated by Django 2.1.7 on 2019-03-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('roll', models.CharField(max_length=128)),
                ('number', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('field', models.CharField(max_length=128)),
                ('ftime', models.DateTimeField()),
                ('ttime', models.DateTimeField()),
                ('purpose', models.TextField()),
            ],
        ),
    ]
