# Generated by Django 2.1.7 on 2019-03-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20190323_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field_book',
            name='ftime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='field_book',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='field_book',
            name='ttime',
            field=models.TimeField(),
        ),
    ]
