# Generated by Django 2.1.7 on 2019-03-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20190326_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='field_book',
            name='status',
            field=models.CharField(default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='field_book',
            name='field',
            field=models.CharField(choices=[('Cricket Field', 'Cricket Field'), ('Football Field', 'Football Field'), ('Badminton Court', 'Badminton Court'), ('Basketball Court', 'Basketball Court'), ('Hockey Field', 'Hockey Field'), ('Tennis Court', 'Tennis Court'), ('Athletic Field', 'Athletic Field'), ('Vollyball Court', 'Vollyball Court')], default=None, max_length=128),
        ),
    ]
